version: "3.7"

x-base: &base
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/scope/.Xauthority
    - YARP_FORWARD_LOG_ENABLE=1
    - QT_X11_NO_MITSHM=1
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/home/scope/.Xauthority:rw"
    - "${HOME}/.config/yarp:/home/scope/.config/yarp:rw"
    - "${HOME}/.local/share/yarp:/home/scope/.local/share/yarp:rw"
    - logs-volume:/home/scope/logs
  network_mode: host
  ipc: host
  security_opt:
    - apparmor:unconfined

x-yarp-mesa-base: &yarp-mesa-base
  <<: *base
  image: scoperobmosys/yarp-mesa:latest

x-qscxml-base: &qscxml-base
  <<: *base
  image: scoperobmosys/qscxml:latest

x-navigation-base: &navigation-base
  <<: *base
  image: scoperobmosys/navigation:latest

x-navigation-gazebo-base: &navigation-gazebo-base   # !add
  <<: *base
  image: scoperobmosys/navigation-gazebo:latest

x-bt-implementation-base: &bt-implementation-base
  <<: *base
  image: bt-implementation:latest

x-build-base: &build-base
  context: .
  args:
    username: scope
    cmake_parallel: 8


services:

# Images
  yarp-mesa:
    <<: *yarp-mesa-base
    build:
      <<: *build-base
      dockerfile: Dockerfile.yarp-mesa

  navigation:
    <<: *navigation-base
    build:
      <<: *build-base
      dockerfile: Dockerfile.navigation
    depends_on:
      - yarp-mesa

  navigation-gazebo:                         # !add
    <<: *navigation-gazebo-base
    build:
      <<: *build-base
      dockerfile: Dockerfile.navigation-gazebo
    depends_on:
      - navigation # not needed, just says that this container should be run after navigation container

  qscxml:
    <<: *qscxml-base
    build:
      <<: *build-base
      dockerfile: Dockerfile.qscxml

  bt-implementation:
    <<: *bt-implementation-base
    build:
      <<: *build-base
      dockerfile: Dockerfile.bt-implementation
    depends_on:
      - qscxml


# Containers (just a way to specify containers' name separately, but could be done also within the services declarations)
  yarp-server:
    <<: *yarp-mesa-base
    container_name: yarp-server
    command: yarp server --read

  IdComponent:
    <<: *bt-implementation-base
    container_name: IdComponent
    command: sh -c "
      yarp wait /root;
      /usr/local/src/bt-implementation/build/bin/IdComponent"
    depends_on:
      - yarp-server

  transformServer:
    <<: *yarp-mesa-base
    container_name: transformServer
    command: sh -c "
      yarp wait /root;
      yarpdev --device transformServer --ROS \"(enable_ros_publisher 0)\" \"(enable_ros_subscriber 0)\""
    depends_on:
      - yarp-server

  fakeMotionControl:
    <<: *yarp-mesa-base
    container_name: fakeMotionControl
    command: sh -c "
      yarp wait /root;
      yarpdev --device fakeMotionControl --name /robot_2wheels/mobile_base --GENERAL::Joints 2"
    depends_on:
      - yarp-server

  baseControl:
    <<: *navigation-base
    container_name: baseControl
    command: sh -c "
      yarp wait /root;
      yarp wait /robot_2wheels/mobile_base/command:i;
      yarp wait /robot_2wheels/mobile_base/rpc:i;
      yarp wait /robot_2wheels/mobile_base/stateExt:o;
      baseControl --context baseControl_SIM --from robot_2wheels.ini --skip_robot_interface_check"
    depends_on:
      - yarp-server
      - fakeMotionControl

  map2DServer:
    <<: *navigation-base
    container_name: map2DServer
    command: sh -c "
      yarp wait /root;
      yarpdev --device map2DServer --mapCollectionContext mapsExample"
    depends_on:
      - yarp-server

  localization2DServer:
    <<: *navigation-base
    container_name: localization2DServer
    command: sh -c "
      yarp wait /root;
      yarp wait /baseControl/odometry:o;
      yarpdev --device localization2DServer --subdevice odomLocalizer --context robotPathPlannerExamples --from odomLocalizer.ini"
    depends_on:
      - yarp-server
      - baseControl

  Rangefinder2DWrapper:
    <<: *navigation-base
    container_name: Rangefinder2DWrapper
    command: sh -c "
      yarp wait /root;
      yarp wait /localizationServer/rpc;
      yarpdev --device Rangefinder2DWrapper --subdevice fakeLaser --period 10 --name /robot_2wheels/laser:o --test use_mapfile --map_file /usr/local/share/navigation/contexts/mapsExample/map_test.map --localization_client"
    depends_on:
      - yarp-server
      - localization2DServer

  navigation2DServer:
    <<: *navigation-base
    container_name: navigation2DServer
    command: sh -c "
      yarp wait /root;
      yarp wait /baseControl/control:i;
      yarp wait /localizationServer/rpc;
      yarp wait /robot_2wheels/laser:o;
      yarp wait /robot_2wheels/laser:o/rpc:i;
      yarp wait /mapServer/rpc;
      yarpdev --device navigation2DServer --subdevice robotPathPlannerDev --context robotPathPlannerExamples --from robotPathPlanner_robot_2wheels.ini"
    depends_on:
      - yarp-server
      - baseControl
      - localization2DServer
      - Rangefinder2DWrapper
      - map2DServer

 #roscore: not found
      #sudo xhost +;
      #nvidia-docker run --rm -it --gpus all -e QT_X11_NO_MITSHM=1 -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics 35aa8288cbff;

  navigationGazeboServer:
    <<: *navigation-gazebo-base
    container_name: navigationGazeboServer
    command: sh -c "
      roscore &
      sleep 1;
      yarp server --ros &
      sleep 1;
      gazebo --verbose /workspace/r1world.world &
      sleep 3;"
    depends_on:
      - yarp-server
      - baseControl
      - localization2DServer
      - Rangefinder2DWrapper
      - map2DServer

  navigationGUI:
    <<: *navigation-base
    container_name: navigationGUI
    command: sh -c "
      yarp wait /root;
      yarp wait /localizationServer/rpc;
      yarp wait /navigationServer/rpc;
      yarp wait /robot_2wheels/laser:o/rpc:i;
      yarp wait /robot_2wheels/laser:o;
      yarp wait /mapServer/rpc;
      navigationGUI --context navigationGUI --from navigationGUI_robot_2wheels.ini"
    depends_on:
      - yarp-server
      - localization2DServer

  yarpview:
    <<: *yarp-mesa-base
    container_name: yarpview
    command: sh -c "
      yarp wait /root;
      yarp view /navigationGui/map:o;
      yarp view /navigationGui/yarpviewTarget:i;
      yarpview --autosize --name /navView:i --out /mapClick:o"
    depends_on:
      - yarp-server
      - navigationGUI

  robotPathPlannerExample:
    <<: *navigation-base
    container_name: robotPathPlannerExample
    command: sh -c "
      yarp wait /root;
      yarp wait /localizationServer/rpc;
      robotPathPlannerExample --navServer_name /navigationServer"
    depends_on:
      - yarp-server
      - localization2DServer

#yarp connect /robotGoto/control:o /gazebo/baseControl/control:i udp; # !add
  connect:
    <<: *yarp-mesa-base
    container_name: connect
    command: sh -c "
      yarp wait /root;
      yarp wait /robotGoto/control:o;
      yarp wait /baseControl/control:i;
      yarp wait /navigationGui/map:o;
      yarp wait /navView:i;
      yarp wait /robotPathPlanner/commands:o;
      yarp wait /robotGoto/rpc;
      yarp wait /mapClick:o
      yarp wait /navigationGui/yarpviewTarget:i;
      yarp connect /robotGoto/control:o /baseControl/control:i udp;
      yarp connect /navigationGui/map:o /navView:i udp;
      yarp connect /robotPathPlanner/commands:o /robotGoto/rpc tcp;
      yarp connect /mapClick:o /navigationGui/yarpviewTarget:i tcp;"
    depends_on:
      - yarp-server
      - navigation2DServer
      - baseControl
      - navigationGUI
      - yarpview
      - robotPathPlannerExample

  GoToComponent:
    <<: *bt-implementation-base
    container_name: GoToComponent
    command: sh -c "
      yarp wait /root;
      yarp wait /navigationServer/rpc;
      yarp wait /mapServer/rpc;
      yarp wait /localizationServer/rpc;
      /usr/local/src/bt-implementation/build/bin/GoToComponent"
    depends_on:
      - yarp-server
      - navigation2DServer
      - map2DServer
      - localization2DServer

  GoToDestination:
    <<: *bt-implementation-base
    container_name: GoToDestination
    command: sh -c "
      yarp wait /GoToComponent;
      yarp wait /BlackboardComponent;
      gammaray /usr/local/src/bt-implementation/build/bin/GoToSkill --skill-name GoToDestination --location kitchen"
    depends_on:
      - yarp-server
      - GoToComponent
      - BlackboardComponent

  GoToChargingStation:
    <<: *bt-implementation-base
    container_name: GoToChargingStation
    command: sh -c "
      yarp wait /GoToComponent;
      yarp wait /BlackboardComponent;
      gammaray /usr/local/src/bt-implementation/build/bin/GoToSkill --skill-name GoToChargingStation --location charging_station"
    depends_on:
      - yarp-server
      - GoToComponent
      - BlackboardComponent

  fakeBattery:
    <<: *yarp-mesa-base
    container_name: fakeBattery
    command: sh -c "
      yarp wait /root;
      yarpdev --device fakeBattery --name /fakeBattery"
    depends_on:
      - yarp-server

  fakeBatteryChargingStation:
    <<: *bt-implementation-base
    container_name: fakeBatteryChargingStation
    command: sh -c "
      yarp wait /root;
      yarp wait /navigationServer/rpc;
      yarp wait /mapServer/rpc;
      yarp wait /localizationServer/rpc;
      yarp wait /fakeBattery/rpc:i;
      yarp wait /fakeBattery/data:o;
      yarp wait /fakeBattery/control/rpc:i;
      /usr/local/src/bt-implementation/build/bin/fakeBatteryChargingStation"
    depends_on:
      - yarp-server
      - navigation2DServer
      - map2DServer
      - localization2DServer
      - fakeBattery

  yarpbatterygui:
    <<: *yarp-mesa-base
    container_name: yarpbatterygui
    command: sh -c "
      yarp wait /root;
      yarp wait /fakeBattery/rpc:i;
      yarp wait /fakeBattery/data:o;
      yarpbatterygui --remote /fakeBattery --refresh_period 1.0"
    depends_on:
      - yarp-server
      - fakeBattery

  BatteryComponent:
    <<: *bt-implementation-base
    container_name: BatteryComponent
    command: sh -c "
      yarp wait /root;
      yarp wait /fakeBattery/rpc:i;
      yarp wait /fakeBattery/data:o;
      /usr/local/src/bt-implementation/build/bin/BatteryComponent"
    depends_on:
      - yarp-server
      - fakeBattery

  BatteryLevelSkill:
    <<: *bt-implementation-base
    container_name: BatteryLevelSkill
    command: sh -c "
      yarp wait /root;
      yarp wait /BatteryComponent;
      gammaray /usr/local/src/bt-implementation/build/bin/BatteryLevelSkill"
    depends_on:
      - yarp-server
      - BatteryComponent

  BatteryNotChargingSkill:
    <<: *bt-implementation-base
    container_name: BatteryNotChargingSkill
    command: sh -c "
      yarp wait /BatteryComponent;
      gammaray /usr/local/src/bt-implementation/build/bin/BatteryNotChargingSkill"
    depends_on:
      - yarp-server
      - BatteryComponent


  BlackboardComponent:
    <<: *bt-implementation-base
    container_name: BlackboardComponent
    command: sh -c "
      yarp wait /root;
      cd /usr/local/src/bt-implementation/build/bin && ./BlackboardComponent"
    depends_on:
      - yarp-server


  BehaviorTree:
    <<: *bt-implementation-base
    container_name: BehaviorTree
    command: sh -c "
      yarp wait /GoToDestination/BT_rpc/server;
      yarp wait /GoToChargingStation/BT_rpc/server;
      yarp wait /BatteryLevel/BT_rpc/server;
      yarp wait /BatteryNotCharging/BT_rpc/server;
      cd /usr/local/src/bt-implementation/build/bin && ./from_xml_example"
    depends_on:
      - yarp-server
      - GoToDestination
      - GoToChargingStation
      - BatteryLevelSkill
      - BatteryNotChargingSkill

  groot:
    <<: *qscxml-base
    container_name: groot
    command: Groot --mode monitor
    depends_on:
      - BehaviorTree

volumes:
  logs-volume:
